name: Node js CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  lint:
    runs-on: ubuntu-latest
    needs: shared
    steps:
      - name: run lint
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    needs: shared
    steps:
      - name: run tests
        run: pnpm test
  build:
    runs-on: ubuntu-latest
    needs: [shared, lint, test]
    steps:
      - name: run build
        run: pnpm build
